version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - nest-postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nest-postgres:5432/${POSTGRES_DB}

  nest-postgres:
    image: postgres:14
    container_name: nest-postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  nest-postgres:
    name: nest-postgres-db